#!/usr/bin/env python3
"""Split resources/jsonData/regs.json (the file you edit) into what the watch loads: index.json (asof + group
names/counts) and one g<N>.json per group, plus jsonData.xml and source/Groups.mc to reference them.
The watch holds the index and one group at a time, not the whole dataset: the Descent G1 only gives an app 96 KB.
build.sh runs this before every build. Run by hand: python3 data/split.py"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "resources", "jsonData")


def main():
    d = json.load(open(os.path.join(DATA, "regs.json"), encoding="utf-8"))
    groups = {}  # insertion-ordered: groups appear in first-seen order, as the menu always did
    for f in d["fish"]:
        groups.setdefault(f["group"], []).append({k: v for k, v in f.items() if k != "group"})
    names = list(groups)
    for old in os.listdir(DATA):
        if old.startswith("g") and old.endswith(".json"):
            os.remove(os.path.join(DATA, old))
    for i, g in enumerate(names):
        json.dump(groups[g], open(os.path.join(DATA, f"g{i}.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=0)
    json.dump({"asof": d["asof"], "groups": names, "counts": [len(groups[g]) for g in names]},
              open(os.path.join(DATA, "index.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=0)
    xml = ['    <jsonData id="index" filename="index.json"/>']
    xml += [f'    <jsonData id="g{i}" filename="g{i}.json"/>' for i in range(len(names))]
    open(os.path.join(DATA, "jsonData.xml"), "w").write(
        "<jsonDataResources>\n" + "\n".join(xml) + "\n</jsonDataResources>\n")
    ids = ", ".join(f"Rez.JsonData.g{i}" for i in range(len(names)))
    open(os.path.join(ROOT, "source", "Groups.mc"), "w").write(
        "import Toybox.Lang;\n\n"
        "// Generated by data/split.py from regs.json; edit regs.json and rebuild instead of editing this.\n"
        "//! The jsonData resource holding group i (same order as index.json \"groups\").\n"
        "function groupData(i as Number) as ResourceId {\n"
        f"    return [{ids}][i] as ResourceId;\n"
        "}\n")


if __name__ == "__main__":
    main()
