import Toybox.Lang;

// Generated by data/split.py from regs.json; edit regs.json and rebuild instead of editing this.
//! The jsonData resource holding group i (same order as index.json "groups").
function groupData(i as Number) as ResourceId {
    return [Rez.JsonData.g0, Rez.JsonData.g1, Rez.JsonData.g2, Rez.JsonData.g3, Rez.JsonData.g4, Rez.JsonData.g5, Rez.JsonData.g6][i] as ResourceId;
}
